### ISSUE TITLE
【依頼】ChatSpace挙動確認

### ISSUE THREAD

**Issue by yuhikimura** [yuhikimura/chat-space#12]
#IPアドレス
54.238.113.93

**Comment by keisukekodama** [comment]
ご提出ありがとうございます！
確認させて頂いたところ、以下の不備が見受けられましたので修正をお願いします！

**ビューの崩れ**
**①下線を消し仕様書どおりにしましょう。**
文字の下線を消し、文字の位置関係をmarginやpaddingのpx数を調整して仕様書どおりにしましょう。

**②メッセージの表示での文字の位置を仕様書どおりにしましょう。**
文字の位置関係をmarginやpaddingのpx数を調整して仕様書どおりにしましょう。

**③下線を消し、仕様書どおりにしましょう。**
Editの下線をけし、色を仕様書どおりにしましょう。

<img width="1459" alt="ChatSpace" src="https://user-images.githubusercontent.com/44963290/83958332-4f357980-a8ab-11ea-9f5c-9ab91016f118.png">


お手本

<img width="1439" alt="ChatSpace" src="https://user-images.githubusercontent.com/44963290/83826615-49a72a80-a717-11ea-9cb2-dc52a8f5c189.png">




参考カリキュラム:https://master.tech-camp.in/curriculums/3944
<img width="837" alt="サイドバー" src="https://user-images.githubusercontent.com/44963290/83826704-85da8b00-a717-11ea-92ef-5d45964baf93.png">

<img width="862" alt="メッセージお手本" src="https://user-images.githubusercontent.com/44963290/83826711-8a06a880-a717-11ea-9403-8b349c098f21.png">

<img width="867" alt="ヘッダー" src="https://user-images.githubusercontent.com/44963290/83958389-1053f380-a8ac-11ea-88ba-fee8f80146b2.png">


修正し次第、以下のChatSpace完了報告フォームを再度提出お願いします！
※新しいissueを作っていただく必要はありません
https://docs.google.com/forms/d/e/1FAIpQLSfNKbknajjCthhkGSyIkhspu2hOAxnESHweNLX2LQJdlO5vGw/viewform

**Comment by miyu-yamamoto** [comment]
木村さん、修正と再提出ありがとうございます！
下記の2点の修正が確認できなかったので、再度ご確認をお願いします。

> **②メッセージの表示での文字の位置を仕様書どおりにしましょう。**
> 文字の位置関係をmarginやpaddingのpx数を調整して仕様書どおりにしましょう。
> **③下線を消し、仕様書どおりにしましょう**
> Editの下線をけし、色を仕様書どおりにしましょう。

他は修正ができておりました！あと少し頑張りましょう💪

修正し次第、以下のChatSpace完了報告フォームに再度こちらのissueのURLを記載していただき提出お願いします！
※新しいissueを作っていただく必要はありません
https://docs.google.com/forms/d/e/1FAIpQLSfNKbknajjCthhkGSyIkhspu2hOAxnESHweNLX2LQJdlO5vGw/viewform

**Comment by mo1015** [comment]
再提出ありがとうございます！
挙動確認させて頂いたところ、以下の修正が確認できませんでした。


**②メッセージの表示での文字の位置を仕様書どおりにしましょう。**
→最初のメッセージの上部に余白がない状況です！


修正でき次第、以下のChatSpace完了報告フォームに再度こちらのissueのURLを記載していただき提出お願いします！
※新しいissueを作っていただく必要はありません
https://docs.google.com/forms/d/e/1FAIpQLSfNKbknajjCthhkGSyIkhspu2hOAxnESHweNLX2LQJdlO5vGw/viewform

**Comment by keisukekodama** [comment]
修正ありがとうございます！
確認させて頂きましたが、全く問題ございませんでしたのでLGTMとさせて頂きます🎉
おめでとうございます！

※今後実装に関する質問がありましたら、メンターに確認をお願いします！
